import { CalendarDays, Plus, Store, Users } from 'lucide-react'
import { Button } from '@/components/ui/Button'
import { reservations, restaurants } from '@/mocks/data'
import { formatDateTime } from '@/lib/utils'

export function OwnerDashboardPage({ view }: { view: 'restaurants' | 'reservations' }) {
  const isRestaurants = view === 'restaurants'
  return <div className="mx-auto max-w-6xl"><header className="mb-8 flex items-end justify-between"><div><p className="text-sm font-semibold text-brand">OWNER CONSOLE</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{isRestaurants ? '식당 관리' : '예약 관리'}</h1><p className="mt-2 text-sm text-muted">{isRestaurants ? '등록한 식당 정보와 공개 상태를 관리합니다.' : '식당별 밥 모임과 참여 현황을 확인합니다.'}</p></div>{isRestaurants && <Button className="hidden gap-2 sm:flex"><Plus size={17} />식당 등록</Button>}</header><div className="mb-6 grid gap-4 sm:grid-cols-3">{[{ icon: Store, label: '등록 식당', value: '2' }, { icon: CalendarDays, label: '이번 주 예약', value: '8' }, { icon: Users, label: '참여 예정', value: '21' }].map((item) => <div key={item.label} className="card p-5"><item.icon size={19} className="text-brand" /><p className="mt-5 text-2xl font-semibold">{item.value}</p><p className="mt-1 text-sm text-muted">{item.label}</p></div>)}</div>{isRestaurants ? <div className="card overflow-hidden"><div className="border-b px-6 py-4 text-sm font-semibold">내 식당</div>{restaurants.slice(0, 2).map((item) => <div key={item.id} className="flex items-center gap-4 border-b p-5 last:border-0"><span className="grid size-14 place-items-center rounded-xl bg-brand-soft text-2xl">{item.image}</span><div><p className="font-semibold">{item.name}</p><p className="mt-1 text-sm text-muted">{item.area} · {item.category}</p></div><span className="ml-auto rounded-full bg-sub-soft px-3 py-1 text-xs font-semibold text-brand">운영 중</span></div>)}</div> : <div className="card overflow-hidden"><div className="border-b px-6 py-4 text-sm font-semibold">예약 목록</div>{reservations.map((item) => <div key={item.id} className="grid gap-3 border-b p-5 last:border-0 md:grid-cols-[1fr_1fr_auto] md:items-center"><div><p className="font-semibold">{item.restaurantName}</p><p className="mt-1 text-sm text-muted">{item.hostName} 님의 모임</p></div><p className="text-sm text-muted">{formatDateTime(item.dateTime)}</p><span className="text-sm font-medium">{item.joined}/{item.capacity}명</span></div>)}</div>}</div>
}
